##### use python2.7
###### pip install pysam
#FASTQC
RUNQC: /home/fgao/software/FastQC/fastqc
#TRIMMOMATIC
RUNTRIM: /home/fgao/software/Trimmomatic-0.38/trimmomatic-0.38.jar
#ADAPTOR
ADAPTORSEQ: /home/fgao/software/Trimmomatic-0.38/adapters/TruSeq3-SE.fa
#BOWTIE
RUNBOWTIE: /home/fgao/software/bowtie2-2.3.5.1-linux-x86_64/bowtie2
#BOWTIE INDEX
BOWTIEINDEX: /home/fgao/reference/Mus_musculus/UCSC/mm10/Sequence/Bowtie2Index/genome
#threads
THREADS: 16
#BEDTOOLS
RUNBEDGRAPH: /home/fgao/software/bedtools2/bin/genomeCoverageBed
#SAMTOOLS
RUNSAMTOOLS: /home/fgao/software/samtools-1.9/samtools
#HOMERTAG
HOMERTAG: /home/fgao/software/homer/bin/makeTagDirectory
#HOMERTRACK
HOMERTRACK: /home/fgao/software/homer/bin/makeUCSCfile
#HOMERPEAK
HOMERPEAK: /home/fgao/software/homer/bin/findPeaks
